### ISSUE TITLE
Update procedure of the project

### ISSUE THREAD

**Issue by mgrbyte** [netsight/emacs.d#25]
@adamcheasley I've been thinking about our chat about updating emacs.d.
I think perhaps what we should do is make it such that the install/update procedure:

```bash
cd ~/.emacs.d
make
```
does **not** [update your emacs packages](https://github.com/netsight/emacs.d/blob/master/Makefile#L17)
This would reduce the chances of upgrading breaking your local emacs config (Due to upstream updates).
This would mean only changes we make would effect your local emacs installation.

We could go further and pin the versions of packages installed, but I think that's too intrusive.
I think basically:
  1. Users should be in charge of which packages (from Melpa/Marmalade/Package manager) they want to use.
  2. Netsight emacs should only install and configure packages that are required by Netisght configuration.
 3. Netsighgt emacs should only configure packages that directly effect netsight development 'policy'.
    (currenlty there are a few places where this is not the case) 

If you agree, will add a PR.

**Comment by adamcheasley** [comment]
I agree!
